import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { sha256 } from '../lib/digests.mjs';
import { parseStrictJson } from '../lib/strict-json.mjs';
import { root, slash, walk } from './files.mjs';

const outputRoot = process.env.AAS_GENERATE_ROOT ? path.resolve(process.env.AAS_GENERATE_ROOT) : root;
const versionMatrix = parseStrictJson(await readFile(path.join(root, 'version-matrix.json')));
const registryValuesPath = 'schemas/registry-values.schema.json';
const registryEntries = async (name) => parseStrictJson(await readFile(path.join(root, `registries/${name}.json`))).entries;
const actionIds = (await registryEntries('actions')).map(({ id }) => id);
const problemCodes = (await registryEntries('problems')).map(({ id }) => id);
const profileBranches = (await registryEntries('profiles')).map(({ id, role, profileAasIdentity }) => {
  const match = /@((?:0|[1-9][0-9]*)(?:\.(?:0|[1-9][0-9]*)){0,2})$/u.exec(id);
  if (!match) {throw new Error(`registered profile ID does not end in its definition version: ${id}`);}
  return { role,
    schema: {
    type: 'object', additionalProperties: false, required: ['version', 'id', 'aasIdentity'],
    properties: {
      version: { const: match[1] }, id: { const: id },
      aasIdentity: profileAasIdentity === undefined ? { $ref: 'common.schema.json#/$defs/aasIdentity' } : { const: profileAasIdentity }
    }}
  };
});
const profileSchemaForRole = (role) => {
  const branches = profileBranches.filter((item) => item.role === role).map((item) => item.schema);
  if (branches.length === 0) {throw new Error(`profile role has no registry entries: ${role}`);}
  return { oneOf: branches };
};
const diagnosticCodes = (await registryEntries('diagnostics')).map(({ id }) => id);
const registryValuesSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://schemas.aas.invalid/private/v0/registry-values.schema.json',
  title: 'Generated AAS closed registry wire values',
  'x-aas-status': 'private-provisional-unpublished',
  $comment: 'Generated by scripts/generate.mjs from registries; do not edit by hand.',
  $defs: {
    actionId: { enum: actionIds }, problemCode: { enum: problemCodes },
    diagnosticCode: { enum: diagnosticCodes },
    canonicalizationProfile: profileSchemaForRole('canonicalization'),
    snapshotCaptureProfile: profileSchemaForRole('snapshot-capture'),
    portablePathProfile: profileSchemaForRole('portable-path'),
    accountingProfile: profileSchemaForRole('accounting')
  },
  type: 'object', additionalProperties: false, maxProperties: 0
};
await mkdir(path.join(outputRoot, 'schemas'), { recursive: true });
await writeFile(path.join(outputRoot, registryValuesPath), JSON.stringify(registryValuesSchema, null, 2) + '\n', 'utf8');
const schemaPaths = (await walk('schemas')).filter((item) => item.endsWith('.schema.json'));
const schemaMap = new Map();
for (const schemaPath of schemaPaths) {
  const sourceRoot = schemaPath === registryValuesPath ? outputRoot : root;
  schemaMap.set(path.basename(schemaPath), parseStrictJson(await readFile(path.join(sourceRoot, schemaPath))));
}

const literal = (value) => JSON.stringify(value);
const typeName = (value) => value.replace(/[^A-Za-z0-9_$]/g, '_');
const intersectSchemas = (left, right) => left === undefined ? right : { allOf: [left, right] };
const makeBranch = (source, key, values, effect = {}) => {
  if (values.length === 0) {return;}
  const branch = { ...source, properties: { ...source.properties }, required: [...(source.required ?? [])] };
  const selection = values.length === 1 ? { const: values[0] } : { enum: values };
  branch.properties[key] = intersectSchemas(branch.properties[key], selection);
  const required = new Set(branch.required);
  for (const [property, constraint] of Object.entries(effect.properties ?? {})) {
    if (constraint === false) { delete branch.properties[property]; required.delete(property); }
    else {branch.properties[property] = intersectSchemas(branch.properties[property], constraint);}
  }
  for (const property of effect.required ?? []) {required.add(property);}
  branch.required = [...required];
  return branch;
  };
function plainObjectType(schema, document) {
  if ((schema.additionalProperties === false || schema.additionalProperties === undefined) && Object.keys(schema.properties ?? {}).length === 0 && schema.maxProperties === 0) {
    return 'Record<PropertyKey, never>';
  }
  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties ?? {}).map(([key, value]) => `  ${JSON.stringify(key)}${required.has(key) ? '' : '?'}: ${typeFor(value, document)};`);
  if (schema.additionalProperties && schema.additionalProperties !== false) {fields.push(`  [key: string]: ${schema.additionalProperties === true ? 'JsonValue' : typeFor(schema.additionalProperties, document)};`);}
  return `{\n${fields.join('\n')}\n}`;
}

function conditionalObjectType(schema, document) {
  if (!Array.isArray(schema.allOf) || schema.allOf.length === 0) {return;}
  const conditionals = schema.allOf;
  if (conditionals.some((conditional) => Object.keys(conditional.if?.properties ?? {}).length !== 1 || !conditional.then)) {return;}
  const base = { ...schema, properties: { ...schema.properties }, required: [...(schema.required ?? [])] };
  delete base.allOf;
  let branches = [{ schema: base, selections: new Map() }];
  for (const conditional of conditionals) {
    const [[key, selection]] = Object.entries(conditional.if.properties);
    const baseSelection = schema.properties?.[key];
    const allValues = baseSelection?.enum ?? ('const' in (baseSelection ?? {}) ? [baseSelection.const] : undefined);
    const selected = selection.enum ?? ('const' in selection ? [selection.const] : undefined);
    if (!allValues || !selected) {return;}
    const selectedSet = new Set(selected);
    branches = branches.flatMap((branch) => {
      const compatibleValues = branch.selections.has(key) ? [branch.selections.get(key)] : allValues;
      return compatibleValues.map((value) => {
        const effect = selectedSet.has(value) ? conditional.then : conditional.else;
        const schemaBranch = makeBranch(branch.schema, key, [value], effect);
        if (!schemaBranch) {return null;}
        const selections = new Map(branch.selections); selections.set(key, value);
        return { schema: schemaBranch, selections };
      }).filter(Boolean);
    });
  }
  return branches.map((branch) => `(${plainObjectType(branch.schema, document)})`).join(' | ');
}
function typeFor(schema, document) {
  if (schema === true) {return 'JsonValue';}
  if (schema === false) {return 'never';}
  if (schema.$ref) {
    const [file, pointer = ''] = schema.$ref.split('#');
    const segments = pointer.split('/').filter(Boolean).map((key) => key.replace(/~1/g, '/').replace(/~0/g, '~'));
    if (segments.length !== 2 || segments[0] !== '$defs' || !segments[1]) {throw new Error(`unsupported generation pointer: ${schema.$ref}`);}
    const targetDocument = file ? schemaMap.get(file) : document;
    if (!targetDocument?.$defs?.[segments[1]]) {throw new Error(`unknown generation $ref: ${schema.$ref}`);}
    const referenced = typeName(segments[1]);
    if (!file) {return referenced;}
    const moduleName = `./${path.basename(file, '.schema.json')}.js`;
    return `import(${JSON.stringify(moduleName)}).${referenced}`;
  }
  if ('const' in schema) {return literal(schema.const);}
  if (schema.enum) {return schema.enum.map(literal).join(' | ');}
  if (schema.oneOf || schema.anyOf) {return (schema.oneOf ?? schema.anyOf).map((item) => `(${typeFor(item, document)})`).join(' | ');}
  if (Array.isArray(schema.type)) {return schema.type.map((item) => typeFor({ ...schema, type: item }, document)).join(' | ');}
  if (schema.type === 'string') {return 'ConstrainedString';}
  if (schema.type === 'integer') {return 'JsonInteger';}
  if (schema.type === 'number') {throw new Error('unbounded JSON Schema number would widen strict I-JSON declarations');}
  if (schema.type === 'boolean') {return 'boolean';}
  if (schema.type === 'null') {return 'null';}
  if (schema.type === 'array') {return `Array<${typeFor(schema.items ?? true, document)}>`;}
  if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    return conditionalObjectType(schema, document) ?? plainObjectType(schema, document);
  }
  if (schema.allOf) {return schema.allOf.map((item) => `(${typeFor(item, document)})`).join(' & ');}
  throw new Error(`unsupported schema shape in ${document.$id ?? '<anonymous>'}`);
}
await mkdir(path.join(outputRoot, 'generated'), { recursive: true });
for (const schemaPath of schemaPaths) {
  const schema = schemaMap.get(path.basename(schemaPath));
  const name = schema.title.replace(/[^A-Za-z0-9]+/g, ' ').trim().replace(/(?:^|\s)([a-z])/g, (_, c) => c.toUpperCase()).replace(/\s/g, '');
  const definitions = Object.entries(schema.$defs ?? {}).map(([definitionName, definition]) => `export type ${typeName(definitionName)} = ${typeFor(definition, schema)};`).join('\n\n');
  const preamble = `/* Generated from ${schemaPath}; JSON Schema is normative. Do not edit. */\n\nexport type ConstrainedString = string & { readonly __aasConstrainedString: unique symbol };\nexport type JsonInteger = number & { readonly __aasSafeInteger: unique symbol };\nexport type JsonValue = null | boolean | ConstrainedString | JsonInteger | JsonValue[] | { [key: string]: JsonValue };\n`;
  const declaration = `${preamble}\n${definitions}${definitions ? '\n\n' : ''}export type ${name} = ${typeFor(schema, schema)};\n`;
  const filename = path.basename(schemaPath, '.schema.json') + '.d.ts';
  await writeFile(path.join(outputRoot, 'generated', filename), declaration.replace(/\r\n?/g, '\n'), 'utf8');
}

const candidates = [
  ...schemaPaths,
  ...(await walk('schemas')).filter((item) => item.endsWith('.md')),
  ...(await walk('registries')).filter((item) => item.endsWith('.json')),
  ...(await walk('registries')).filter((item) => item.endsWith('.md')),
  ...(await walk('profiles')),
  ...(await walk('spec')).filter((item) => item.endsWith('.md')),
  'decisions/README.md',
  'decisions/phase-0-d0-d11-v1.md',
  'decisions/phase-0-d0-d11-v2.md',
  'decisions/phase-1-p1-remediation-v1.md',
  ...(await walk('docs/decisions')).filter((item) => item.endsWith('.md')),
  'templates/normative-traceability.md',
  ...(await walk('vectors')),
  'version-matrix.json',
  ...schemaPaths.map((item) => `generated/${path.basename(item, '.schema.json')}.d.ts`)
];
const unique = [...new Set(candidates)].toSorted();
const artifacts = [];
for (const relative of unique) {
  const sourceRoot = relative.startsWith('generated/') || relative === registryValuesPath ? outputRoot : root;
  const bytes = await readFile(path.join(sourceRoot, relative));
  const extension = path.extname(relative);
  const entry = {
    path: slash(relative),
    class: relative.startsWith('schemas/') && relative.endsWith('.json') ? 'schema'
      : relative.startsWith('registries/') && relative.endsWith('.json') ? 'registry'
      : relative.startsWith('profiles/') ? 'profile-definition'
      : relative.startsWith('vectors/') && relative !== 'vectors/readme.md' ? 'vector'
      : relative.startsWith('generated/') ? 'generated-declaration'
      : relative.startsWith('docs/decisions/') ? 'decision-provenance'
      : relative === 'version-matrix.json' ? 'version-matrix' : 'normative-prose',
    contentDigest: sha256(bytes),
    aasIdentityStatus: 'not-computed-phase-1',
    byteLength: bytes.byteLength,
    mediaType: extension === '.json' ? 'application/json' : extension === '.md' ? 'text/markdown' : 'text/typescript'
  };
  if (entry.class === 'schema') {entry.schemaId = parseStrictJson(bytes).$id;}
  artifacts.push(entry);
}
const manifest = {
  manifestVersion: '1',
  standardVersion: versionMatrix.standardVersion,
  status: 'provisional-unpublished',
  schemaDialect: 'https://json-schema.org/draft/2020-12/schema',
  identityPolicy: {
    contentDigest: 'raw-sha256-over-exact-content-bytes',
    aasIdentity: 'domain-framed-identity-deferred-to-phase-2'
  },
  artifacts
};
await writeFile(path.join(outputRoot, 'artifacts.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
